


--FOR AUTOINCREMENT
--https://www.youtube.com/watch?v=NqD7rDydS8I&ab_channel=TableauTip



--DROP TABLE PRODUCT_COMPUTER;
--DROP TABLE PRODUCT_HEADPHONES;
--DROP TABLE PRODUCT_PRINTER;
--DROP TABLE PRODUCT_PENDRIVE;
--DROP TABLE PRODUCT_CATAGORY;
--DROP SEQUENCE PRODUCT_ID;
--DROP SEQUENCE CATAGORY_ID;

CREATE TABLE PRODUCT_CATAGORY(
CATAGORY_ID INT NOT NULL,
CATAGORY_NAME VARCHAR(30) NOT NULL,
CATAGORY_TAG1 VARCHAR(10) NOT NULL,
CATAGORY_TAG2 VARCHAR(10) NOT NULL,
CATAGORY_TAG3 VARCHAR(10) NOT NULL,
CATAGORY_TAG4 VARCHAR(10) NULL,
CATAGORY_TAG5 VARCHAR(10) NULL,
CATAGORY_TAG6 VARCHAR(10) NULL,
PRIMARY KEY(CATAGORY_ID)
);
CREATE SEQUENCE CATAGORY_ID MINVALUE 2000 START WITH 2000 CACHE 10;

CREATE TABLE PRODUCT_COMPUTER (
PRODUCT_ID_COMPUTER INT,
PRODUCT_NAME VARCHAR (100) NOT NULL,
PRODUCT_CATAGORY_ID INT NOT NULL,
PRODUCT_QUANTITY INT NOT NULL,
PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
PRODUCT_TAG1 VARCHAR(10) NOT NULL,
PRODUCT_TAG2 VARCHAR(10) NOT NULL,
PRODUCT_TAG3 VARCHAR(10) NULL,
PRIMARY KEY (PRODUCT_ID_COMPUTER),
FOREIGN KEY (PRODUCT_CATAGORY_ID) REFERENCES PRODUCT_CATAGORY(CATAGORY_ID)
);
CREATE SEQUENCE PRODUCT_ID_COMPUTER MINVALUE 1 START WITH 1 CACHE 10;

CREATE TABLE PRODUCT_HEADPHONES (
PRODUCT_ID_HEADPHONES INT,
PRODUCT_NAME VARCHAR (100) NOT NULL,
PRODUCT_CATAGORY_ID INT NOT NULL,
PRODUCT_QUANTITY INT NOT NULL,
PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
PRODUCT_TAG1 VARCHAR(10) NOT NULL,
PRODUCT_TAG2 VARCHAR(10) NOT NULL,
PRODUCT_TAG3 VARCHAR(10) NULL,
PRIMARY KEY(PRODUCT_ID_HEADPHONES),
FOREIGN KEY (PRODUCT_CATAGORY_ID) REFERENCES PRODUCT_CATAGORY(CATAGORY_ID)
);

CREATE SEQUENCE PRODUCT_ID_HEADPHONES MINVALUE 1000 START WITH 1000 CACHE 10;

CREATE TABLE PRODUCT_PRINTER (
PRODUCT_ID_PRINTER INT,
PRODUCT_NAME VARCHAR (100) NOT NULL,
PRODUCT_CATAGORY_ID INT NOT NULL,
PRODUCT_QUANTITY INT NOT NULL,
PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
PRODUCT_TAG1 VARCHAR(10) NOT NULL,
PRODUCT_TAG2 VARCHAR(10) NOT NULL,
PRODUCT_TAG3 VARCHAR(10) NULL,
PRIMARY KEY (PRODUCT_ID_PRINTER),
FOREIGN KEY (PRODUCT_CATAGORY_ID) REFERENCES PRODUCT_CATAGORY(CATAGORY_ID)
);

CREATE SEQUENCE PRODUCT_ID_PRINTER MINVALUE 5000 START WITH 5000 CACHE 10;

CREATE TABLE PRODUCT_PENDRIVE (
PRODUCT_ID_PENDRIVE INT,
PRODUCT_NAME VARCHAR (100) NOT NULL,
PRODUCT_CATAGORY_ID INT NOT NULL,
PRODUCT_QUANTITY INT NOT NULL,
PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
PRODUCT_TAG1 VARCHAR(10) NOT NULL,
PRODUCT_TAG2 VARCHAR(10) NOT NULL,
PRODUCT_TAG3 VARCHAR(10) NULL,
PRIMARY KEY (PRODUCT_ID_PENDRIVE),
FOREIGN KEY (PRODUCT_CATAGORY_ID) REFERENCES PRODUCT_CATAGORY(CATAGORY_ID)
);

CREATE SEQUENCE PRODUCT_ID_PENDRIVE MINVALUE 6000 START WITH 6000 CACHE 10;

COMMIT;
