
create or replace function isMatchedEmployer(EMP_EMAIL in EMPLOYER.EMPLOYER_EMAIL%TYPE)
  return EMPLOYER.EMPLOYER_ID%TYPE
  is
	EMP_ID EMPLOYER.EMPLOYER_ID%TYPE :=0;
	COUNT_ROW NUMBER;
begin
	
	SELECT COUNT(*) INTO COUNT_ROW FROM EMPLOYER WHERE EMPLOYER_EMAIL = EMP_EMAIL;
	
	IF COUNT_ROW = 0 THEN
		RETURN EMP_ID;
	ELSE 
		SELECT EMPLOYER_ID INTO EMP_ID FROM EMPLOYER WHERE EMPLOYER_EMAIL = EMP_EMAIL;
		RETURN EMP_ID ;
	END IF;
	
end isMatchedEmployer;
/
commit;

