set SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER INSERT_CUSTOMER_TABLE_LOG
AFTER INSERT ON CUSTOMER
FOR EACH ROW

BEGIN
DBMS_OUTPUT.PUT_LINE('SUCCESSFULLY DATA INSERTED IN CUSTOMER TABLE');
INSERT INTO LOG_INSERT_CUSTOMER VALUES (:NEW.CUSTOMER_ID,SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER BUYING_DETAILS_TABLE_LOG
AFTER INSERT ON BUYING_DETAILS
FOR EACH ROW

BEGIN
DBMS_OUTPUT.PUT_LINE('SUCCESSFULLY DATA INSERTED IN BUYING_DETAILS TABLE');
INSERT INTO LOG_INSERT_CUSTOMER VALUES (:NEW.PURCHASE_ID,SYSDATE);
END;
/
commit;