--view for all computer ids
CREATE OR REPLACE VIEW PRODUCT_ALL_IDS AS SELECT PRODUCT_ID_COMPUTER  FROM PRODUCT_COMPUTER@site_link ;
--view for all catagorys
CREATE OR REPLACE VIEW PRODUCT_CATAGORYS AS select CATAGORY_NAME FROM PRODUCT_CATAGORY@site_link;
